### PR TITLE
first attempt at atoms -> strings (Issue #16)

### PR DESCRIPTION
**Pull request by ghost**
Hi, I don't know if your interested but lets see - I've been working with graphql a lot recently and it's really tedious to have to convert back and forth, back and forth between string -> atom -> string keys. 

Your library is great, but I need something to convert in the opposite direction - i.e. atoms to string keys. 

Perhaps this change is usefull, any feedback appreciated - I've left of adding docs while I wait for feedback.

### CODE REVIEW

**Comment by philosodad** [comment]
I am definitely interested in this pull request, I'll try and look at it today or tomorrow. There might be some conflicts as master has updated. One thing I've been trying to do is get code moved out of the main module (like the Utils.Equality module) so if you wanted to look at what's changed and make sure this PR is out of conflict with the current code that would be helpful.

**Comment by philosodad** [comment]
Also, can you add a non-recursive version? This should be pretty easy, I think the code from atomorphif* should show you the way.

**Review by philosodad — CHANGES_REQUESTED** [review]
I've rebased changes from master onto a new branch for this, if you could add the non-recursive function (stringmorphify) and add some documentation from that branch I think we can merge that onto master.

new branch: https://github.com/philosodad/morphix/tree/bryanhuntesl-feature/atoms-to-strings

**Comment by ghost** [comment]
Hey @philosodad - thanks for that - I'll take a look at it now.

**Pull request closed without merging**
